using Trustedbits.ApiServer.Models;
using Trustedbits.ApiServer.Models.DTOs;

namespace Trustedbits.ApiServer.Services.Interfaces;

/// <summary>
/// Specialization of <see cref="ServiceResult{TErrorEnum,TSuccess}"/> class for role-related
/// operations.
/// </summary>
/// <typeparam name="TSuccess">Type of the data to return when the called succeeds</typeparam>
public class RoleServiceResult<TSuccess> : ServiceResult<RoleErrors, TSuccess>
{
    public RoleServiceResult(TSuccess value) : base(value) { }
    public RoleServiceResult(RoleErrors error, ServiceError errorData) : base(error, errorData) { }
}

/// <summary>
/// Possible error outcomes for the role service. They are used by the controller to determine which
/// HTTP code to emit in response.
/// </summary>
public enum RoleErrors
{
    /// <summary>
    /// Provided role name already exists
    /// </summary>
    RoleAlreadyExists,
    /// <summary>
    /// The format of the data is invalid or fields are missing
    /// </summary>
    RoleInvalidData,
    
    /// <summary>
    /// Provided role name cannot be found
    /// </summary>
    RoleNotFound,
    
    /// <summary>
    /// Error generated by an internal issue (e.g. DB connection fail)
    /// </summary>
    ServerError
}


public interface IRoleService
{
    Task<RoleServiceResult<RoleDto>> CreateRole(Guid tenantId, RoleDto roleDto);
    Task<RoleServiceResult<IEnumerable<RoleDto>>> GetAll(Guid tenantId);
    Task<RoleServiceResult<RoleDto>> EditRole(Guid tenantId, string roleName, RoleDto roleDto);
    Task<RoleServiceResult<bool>> DeleteRole(Guid tenantId, string roleName);
}