using Trustedbits.ApiServer.Models;
using Trustedbits.ApiServer.Models.DTOs;

namespace Trustedbits.ApiServer.Services.Interfaces;

/// <summary>
/// Specialization of <see cref="ServiceResult{TErrorEnum,TSuccess}"/> class for scope-related
/// operations.
/// </summary>
/// <typeparam name="TSuccess">Type of the data to return when the called succeeds</typeparam>
public class ScopeServiceResult<TSuccess> : ServiceResult<ScopeErrors, TSuccess>
{
    public ScopeServiceResult(TSuccess value) : base(value) { }
    public ScopeServiceResult(ScopeErrors error, ServiceError errorData) : base(error, errorData) { }
}

/// <summary>
/// Possible error outcomes for the scope service. They are used by the controller to determine which
/// HTTP code to emit in response.
/// </summary>
public enum ScopeErrors
{
    /// <summary>
    /// Provided scope name (or other value) already exists
    /// </summary>
    ScopeAlreadyExists,
    /// <summary>
    /// The format of the data is invalid or fields are missing
    /// </summary>
    ScopeInvalidData,
    
    /// <summary>
    /// Provided scope name cannot be found
    /// </summary>
    ScopeNotFound,
    
    /// <summary>
    /// Error generated by an internal issue (e.g. DB connection fail)
    /// </summary>
    ServerError
}

// Formal contract for the scope management service. Since the scope name must be unique, this value is used
// as the main query parameter.
public interface IScopeService
{
    /// <summary>
    /// Create a new scope in the tenant
    /// </summary>
    /// <param name="tenantId">UUID of the tenant associated with the new scope </param>
    /// <param name="scopeDto">Contain infos about the new scope (<see cref="ScopeDto"/>) </param>
    /// <returns>
    /// If succeeded, returns a DTO containing the new scope data, else a description of the error
    /// <see cref="ServiceError"/> and docs/ERRORS.md
    /// </returns>
    Task<ScopeServiceResult<ScopeDto>> CreateScope(Guid tenantId, ScopeDto scopeDto);
    
    /// <summary>
    /// Retrieve a single scope information by querying with search parameters (name, keywords in name, value)
    /// </summary>
    /// <param name="tenantId">UUID of the tenant associated with the scope</param>
    /// <param name="scopeQueryData">DTO containing the data for query the scope</param>
    /// <returns>If succeeded, the DTO with the scope information, else a <see cref="ScopeErrors.ScopeNotFound"/> error</returns>
    Task<ScopeServiceResult<List<ScopeDto>>> GetScope(Guid tenantId, ScopeQueryDto scopeQueryData);

    /// <summary>
    /// Get a paginated list of all the scopes registered for the tenant.
    /// </summary>
    /// <param name="tenantId">UUID of the tenant</param>
    /// <param name="page">Number of the page</param>
    /// <param name="pageSize">How many elements a page contain</param>
    /// <returns>List of all the scopes in the provided tenant</returns>
    Task<ScopeServiceResult<List<ScopeDto>>> GetAllScopes(Guid tenantId, int page, int pageSize);
    
    /// <summary>
    /// Update information of an existing scope (queried by name)
    /// </summary>
    /// <param name="tenantId">UUID of the tenant associated with the new scope</param>
    /// <param name="scopeName">Name of the scope to edit</param>
    /// <param name="scopeEditData">DTO containing the updated fields</param>
    /// <returns>If succeeded returns the updated DTO, else <see cref="ScopeErrors"/></returns>
    Task<ScopeServiceResult<ScopeDto>> EditScope(Guid tenantId, String scopeName, ScopeDto scopeEditData);
    
    /// <summary>
    /// Delete an existing scope (queried by name)
    /// </summary>
    /// <param name="tenantId">UUID of the tenant associated with the new scope</param>
    /// <param name="scopeName">Name of the scope to delete</param>
    /// <returns>If succeeded returns true, else <see cref="ScopeErrors.ScopeNotFound"/></returns>
    Task<ScopeServiceResult<bool>> DeleteScope(Guid tenantId, String scopeName);
}