using Trustedbits.ApiServer.Core.Dto;
using Trustedbits.ApiServer.Core.Patterns;

namespace Trustedbits.ApiServer.Core.Contracts;

/// <summary>
/// This interface defines the functionalities for managing RBAC roles.
/// </summary>
public interface IRoleService
{
    /// <summary>
    /// Use case of the role service for create new roles.
    /// </summary>
    /// <param name="role">DTO containing new role information</param>
    /// <returns><c>ErrorDto</c>, else the new role DTO with the ID generated by the server</returns>
    Task<Result<RoleDto>> Create(RoleDto role);

    /// <summary>
    /// Use case of the role service for describe an existing role given its ID.
    /// </summary>
    /// <param name="id">ID of the role to describe</param>
    /// <returns><c>ErrorDto</c>, else the role DTO</returns>
    Task<Result<RoleDto>> Get(Guid id);

    /// <summary>
    /// Use case of the role service for list all the roles using paging.
    /// </summary>
    /// <param name="page">Number of page</param>
    /// <param name="pageSize">Number of elements per page</param>
    /// <returns><c>ErrorDto</c>, else a list of role DTOs</returns>
    Task<Result<IEnumerable<RoleDto>>> Get(int page, int pageSize);
    
    /// <summary>
    /// Use case of the role service for list all the roles that contain a certain
    /// term using paging.
    /// </summary>
    /// <param name="term">Term to look up for in name and description of the roles</param>
    /// <param name="page">Number of page</param>
    /// <param name="pageSize">Number of elements per page</param>
    /// <returns><c>ErrorDto</c>, else a list of role DTOs</returns>
    Task<Result<IEnumerable<RoleDto>>> Search(string term, int page, int pageSize);
    
    /// <summary>
    /// Use case of the role service for update an existing role.
    /// </summary>
    /// <param name="id">ID of the role to update</param>
    /// <param name="role">New role information</param>
    /// <returns><c>ErrorDto</c>, else the role state in form of DTO</returns>
    Task<Result<RoleDto>> Update(Guid id, RoleDto role);
    
    /// <summary>
    /// Use case of the role service for delete an existing role.
    /// </summary>
    /// <param name="id">ID of the role to delete</param>
    /// <returns></returns>
    Task<Result<bool>> Delete(Guid id);

    /// <summary>
    /// Use case of the role service for assign a scope to an existing role.
    /// </summary>
    /// <param name="roleId"></param>
    /// <param name="scopeId"></param>
    /// <returns><c>ErrorDto</c>, else true</returns>
    Task<Result<bool>> AssignScope(Guid roleId, Guid scopeId);
    
    /// <summary>
    /// Use case of the role service for revoke a scope to an existing role.
    /// </summary>
    /// <param name="roleId"></param>
    /// <param name="scopeId"></param>
    /// <returns><c>ErrorDto</c>, else true</returns>
    Task<Result<bool>> RevokeScope(Guid roleId, Guid scopeId);
}