using Trustedbits.ApiServer.Core.Dto;
using Trustedbits.ApiServer.Core.Patterns;

namespace Trustedbits.ApiServer.Core.Contracts;

/// <summary>
/// Interface defining the use cases for the Scope service/Unit
/// of Work.
/// </summary>
public interface IScopeService
{
    /// <summary>
    /// Use case of the scope unit of work for creating a new scope.
    /// </summary>
    /// <param name="scope">DTO containing the new scope information.</param>
    /// <returns>New scope information with ID generated by the server.</returns>
    Task<Result<ScopeDto>> Create(ScopeDto scope);
    
    /// <summary>
    /// Use case of the scope unit of work for describing a scope given its ID.
    /// </summary>
    /// <param name="id">ID of the scope to describe.</param>
    /// <returns>DTO containing the information describing the scope.</returns>
    Task<Result<ScopeDto>> Get(Guid id);
    /// <summary>
    ///  Use case of the scope unit of work for describing all scopes using paging.
    /// </summary>
    /// <param name="page">Number of page.</param>
    /// <param name="pageSize">Number of elements per page.</param>
    /// <returns>List of descriptions of all scopes</returns>
    Task<Result<IAsyncEnumerable<ScopeDto>>> Get(int page, int pageSize);
    /// <summary>
    /// Use case of the scope unit of work for searching a scope using a term that might be
    /// in name, value, or description.
    /// </summary>
    /// <param name="term">Term to look up for.</param>
    /// <param name="page">Number of page.</param>
    /// <param name="size">of elements per page.</param>
    /// <returns>List of scope descriptions that contain this term.</returns>
    Task<Result<IEnumerable<ScopeDto>>> Search(string term, int page, int size);
    /// <summary>
    /// Use case of the scope unit of work for updating an existing scope.
    /// </summary>
    /// <param name="id">ID of the scope to update.</param>
    /// <param name="scope">DTO with the new scope information.</param>
    /// <returns>DTO of the new scope with updated information.</returns>
    Task<Result<ScopeDto>> Update(Guid id, ScopeDto scope);
    /// <summary>
    /// Use case of the scope unit of work for delete an existing scope.
    /// </summary>
    /// <param name="id">ID of the scope to delete.</param>
    /// <returns>Boolean describing whether the scope has been deleted.</returns>
    Task<Result<bool>> Delete(Guid id);
}