using Microsoft.AspNetCore.Mvc;
using Trustedbits.ApiServer.Core.Contracts;
using Trustedbits.ApiServer.Core.Dto;
using Trustedbits.ApiServer.Core.Patterns;

namespace Trustedbits.ApiServer.Adapters.Http;

/// <summary>
/// HTTP adapter exposing REST endpoints for role operations.
/// Delegates business logic to an <see cref="IRoleService"/> instance.
/// </summary>
[ApiController]
[Route("/api/roles")]
public class RoleHttpAdapter : ControllerBase
{
    private readonly IRoleService _service;

    /// <summary>
    /// Constructor for Role HTTP Adapter.
    /// </summary>
    /// <param name="service"></param>
    public RoleHttpAdapter(IRoleService service)
    {
        _service = service;
    }
    
    /// <summary>
    /// HTTP adapter for expose <c>IRoleService.Create</c> use case. It creates a role using the information
    /// passed in the body and returns them in the DTO (with a random ID generated by the server).
    /// </summary>
    /// <param name="dto">DTO with new role data</param>
    /// <returns>
    /// 201 with role DTO, or error DTO with error description
    /// </returns>
    [HttpPost]
    public async Task<IActionResult> Create([FromBody] RoleDto dto)
    {
        var result = await _service.Create(dto);
        if (result.IsFailed)
        {
            switch (result.ErrorType)
            {
                case ErrorType.Conflict:
                    return Conflict(result.Error);
                case ErrorType.BadRequest:
                    return BadRequest(result.Error);
            }
        }
        return CreatedAtAction(nameof(Get), new { id = result.Data!.RoleId },  result.Data);
    }
    
    /// <summary>
    /// HTTP adapter for expose <c>IRoleService.Get(id)</c> use case.
    /// </summary>
    /// <param name="id">ID of the role to describe</param>
    /// <returns>
    /// It returns a DTO formatted description of an existing role
    /// queried by its ID, or error DTO with error description
    /// </returns>
    [HttpGet("{id:guid}")]
    public async Task<IActionResult> Get([FromRoute] Guid id)
    {
        var result = await _service.Get(id);
        if (result.IsFailed)
        {
            switch (result.ErrorType)
            {
                case ErrorType.NotFound:
                    return NotFound(result.Error);
                case ErrorType.BadRequest:
                    return BadRequest(result.Error);
            }
        }
        return Ok(result.Data);
    }
    
    /// <summary>
    /// HTTP adapter for expose <c>IRoleService.Get(page, pageSize)</c> use case.
    /// </summary>
    /// <param name="page">Number of page</param>
    /// <param name="pageSize">Number of elements per page</param>
    /// <returns>
    /// It returns a paged list of all roles registered, or error DTO with error description
    /// </returns>
    [HttpGet]
    public async Task<IActionResult> Get([FromQuery] int page, [FromQuery] int pageSize)
    {
        var result = await _service.Get(page, pageSize);
        if (result.IsFailed)
            return BadRequest(result.Error);
        
        return Ok(result.Data);
    }

    /// <summary>
    /// HTTP adapter for expose <c>IRoleService.Search(page, pageSize)</c> use case
    /// </summary>
    /// <param name="query">Term to look up for in the role names and descriptions</param>
    /// <param name="page"></param>
    /// <param name="pageSize"></param>
    /// <returns>
    /// It returns a paged list
    /// of all roles that contain a query term in the role name or the role description,
    /// or error DTO with error description
    /// </returns>
    [HttpGet("search")]
    public async Task<IActionResult> Search([FromQuery] string query, int page, int pageSize)
    {
        var result = await _service.Search(query, page, pageSize);
        if (result.IsFailed)
        {
            return BadRequest(result.Error);
        }
        return Ok(result.Data);
    }
    
    /// <summary>
    /// HTTP adapter for expose <c>IRoleService.Update(id, dto)</c> use case.
    /// </summary>
    /// <param name="id">ID of the scope to update</param>
    /// <param name="dto">DTO containing the fields to update</param>
    /// <returns>
    /// It returns a DTO of the role with updated information, or error DTO with error description
    /// </returns>
    [HttpPatch("{id:guid}")]
    public async Task<IActionResult> Update([FromRoute] Guid id, [FromBody] RoleDto dto)
    {
        var result = await _service.Update(id, dto);
        if (result.IsFailed)
        {
            switch (result.ErrorType)
            {
                case ErrorType.Conflict:
                    return Conflict(result.Error);
                case ErrorType.BadRequest:
                    return BadRequest(result.Error);
                case ErrorType.NotFound:
                    return NotFound(result.Error);
            }
        }
        return Ok(result.Data);
    }

    /// <summary>
    /// HTTP adapter for expose IRoleService.Delete(id) use case.
    /// </summary>
    /// <param name="id">ID of the role to delete</param>
    /// <returns>Empty body, or error DTO with error description</returns>
    [HttpDelete("{id:guid}")]
    public async Task<IActionResult> Delete([FromRoute] Guid id)
    {
        var result = await _service.Delete(id);
        if (result.IsFailed)
        {
            switch (result.ErrorType)
            {
                case ErrorType.NotFound:
                    return NotFound(result.Error);
            }
        }
        return Ok();
    }

    /// <summary>
    /// HTTP adapter for expose IRoleService.Assign(roleId, scopeId) use case.
    /// </summary>
    /// <param name="roleId"></param>
    /// <param name="scopeId"></param>
    /// <returns></returns>
    [HttpPost("{roleId:guid}/scopes")]
    public async Task<IActionResult> AssignScope([FromRoute] Guid roleId, [FromQuery] Guid scopeId)
    {
        var result = await _service.AssignScope(roleId, scopeId);
        if (result.IsFailed)
        {
            switch (result.ErrorType)
            {
                case ErrorType.NotFound:
                    return NotFound(result.Error);
            }
        }
        return Ok();
    }
}